name: Deploy ARM template to Azure Data Factory

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Validate ARM template
        uses: jzagelbaum/data-factory-validate-action@latest
     

      - name: Export Azure Data Factory
        id: export
        uses: jzagelbaum/data-factory-export-action@latest
     
      
      - name: Publish ARM template
        uses: actions/upload-artifact@v3
        with:
          name: adf-armtemplate
          path: ${{ steps.export.outputs.arm-template-directory }}
          if-no-files-found: error
  
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Login via Az module
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          enable-AzPSSession: true 
     
      - name: Download ARM template
        uses: actions/download-artifact@v3
        with:
          name: adf-armtemplate

      - name: Deploy resources
        uses: jzagelbaum/data-factory-deploy-action@latest
        with:
          resourceGroupName: ${{ env.AZURE_RG }} 
          dataFactoryName: ${{ env.AZURE_DATA_FACTORY }} 
