name: Validate and Export ARM Template

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18.x'

    - name: Install npm packages
      run: npm install
      working-directory: ${{github.workspace}}/build # replace with the package.json folder

    - name: Validate Data Factory resources
      run: npm run build validate ${{github.workspace}} /subscriptions/9793767c-06b9-4ee5-bfb5-5849b242f311/resourceGroups/rg-adfdemo/providers/Microsoft.DataFactory/factories/adfghdemojz
      working-directory: ${{github.workspace}}/build # replace with the package.json folder

    - name: Validate and Generate ARM template
      run: npm run build export ${{github.workspace}} /subscriptions/9793767c-06b9-4ee5-bfb5-5849b242f311/resourceGroups/rg-adfdemo/providers/Microsoft.DataFactory/factories/adfghdemojz "ArmTemplate"
      # For using preview that allows you to only stop/start triggers that are modified, uncomment the below line and make sure the package.json contains the build-preview command.
      # run: npm run build-preview export ./<Root-folder-from-Git-configuration-settings-in-ADF> /subscriptions/aaaa0a0a-bb1b-cc2c-dd3d-eeeeee4e4e4e/resourceGroups/GartnerMQ2021/providers/Microsoft.DataFactory/factories/Dev-GartnerMQ2021-DataFactory "ArmTemplate"
      working-directory: ${{github.workspace}}/build # replace with the package.json folder

    - name: Upload ARM template artifact
      uses: actions/upload-artifact@v4
      with:
        name: ArmTemplates
        path: ${{github.workspace}}/build/ArmTemplate # replace with the package.json folder

  release:
    needs: build
    runs-on: windows-latest
#    defaults:
#      run:
#       working-directory: ${{github.workspace}}/release
    steps:

        
 # we 1st download the previously uploaded artifact so we can leverage it later in the release job     
      - name: Download a Build Artifact
        uses: actions/download-artifact@v4
        with:
          name: ArmTemplates # (5) Artifact name 
 #         path: ${{github.workspace}}/release

 #     - name: Display structure of downloaded files
 #       run: ls -R

      - name: Login via Az module
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          enable-AzPSSession: true 
      
   #   - name: Upgrade Az PowerShell module to 13
   #     run: Update-PSResource Az -Force 
   #     shell: pwsh

      - name: Run Azure PowerShell Script File
        uses: azure/powershell@v2
        with:
         inlineScript: |
          ./PrePostDeploymentScript.ps1 `
          -armTemplate ${{github.workspace}}\ARMTemplateForFactory.json `
          -ArmTemplateParameters ${{github.workspace}}\ARMTemplateParametersForFactory.json `
          -ResourceGroupName 'rg-adfdemorelease' `
          -DataFactoryName 'adfdemorelease'`
          -predeployment $true `
          -deleteDeployment $false
         azPSVersion: "latest"
         
  #    - name: Run Pre-deployment script
  #      run: |
  #        ./PrePostDeploymentScript.ps1 `
  #        -armTemplate ${{github.workspace}}\ARMTemplateForFactory.json `
  #        -ArmTemplateParameters ${{github.workspace}}\ARMTemplateParametersForFactory.json `
  #        -ResourceGroupName 'rg-adfdemorelease' `
  #        -DataFactoryName 'adfdemorelease'`
  #        -predeployment $true `
  #        -deleteDeployment $false
  #      shell: pwsh

      - name: Run ARM deploy
        uses: azure/arm-deploy@v2
        with:
         #   scope: 'resourceGroup'
            resourceGroupName: 'rg-adfdemorelease'  
            template: 'ARMTemplateForFactory.json' 
            parameters: ARMTemplateParametersForFactory.json factoryName=adfdemorelease #add additional overide parameters if needed here ''
        
  #    - name: Run Post-deployment script
  #      run: |
  #        ./PrePostDeploymentScript.ps1 `
  #        -armTemplate 'ARMTemplateForFactory.json' `
  #        -ResourceGroupName 'rg-adfdemorelease' `
  #        -DataFactoryName 'adfdemorelease'`
  #        -predeployment $false `
  #        -deleteDeployment $true
  #      shell: pwsh
